version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      SERVICE_TYPE: backend

  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      SERVICE_TYPE: frontend
    depends_on:
      - backend
